---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04

suites:
  - name: duply
    run_list:
      - recipe[apt::default]
      - recipe[fake::default]
    attributes:
