---
driver_plugin: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: debian-7.8

suites:
  - name: duply
    run_list:
      - recipe[fake::default]
    attributes:
